### ISSUE TITLE
Precondition Name is always overwritten in output tab with Step Name

### ISSUE THREAD

**Issue by jdeve** [mfekadu/Excel2Jira#16]
When creating preconditions in the Input Tab, the user customizes the Step Name column to 'Precondition Name'.  When executing the Generate JIRA Markup, the output tab is displayed 'Step Name' vs 'Precondition Name'

**Comment by mfekadu** [comment]
#18 seems to resolve this issue

**Comment by jdeve** [comment]
Closing issue with #18
